name: RSS Processor

on:
  schedule:
    - cron: '*/30 * * * *'  # Запускать каждый час
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install schedule
          pip install feedparser
          pip install beautifulsoup4

      - name: Run rss_processor.py
        run: python rss_processor.py
